// src/reporter/daily-report.js
// Generates a Markdown daily report and saves it to data/reports/.
// This file is committed to the repo and rendered on the web.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { saveDailyRun } from '../db/database.js';

const __dir = path.dirname(fileURLToPath(import.meta.url));
const REPORTS_DIR = path.join(__dir, '../../data/reports');

export function generateDailyReport(date, apps, { skipped = 0 } = {}) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });

  const dateFormatted = new Date(date + 'T12:00:00Z').toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });

  const lines = [
    `# LLM Daily Review — ${dateFormatted}`,
    '',
    `> ${apps.length} app${apps.length !== 1 ? 's' : ''} tested today from Hacker News.`,
    '',
  ];

  if (!apps.length) {
    lines.push('No LLM-related apps found on HN today.');
  } else {
    // Sort by total score descending
    const sorted = [...apps].sort((a, b) => (b.total_score ?? 0) - (a.total_score ?? 0));

    for (const app of sorted) {
      const scores = app.scores || {};
      const badge = { 'strong-candidate': '🟢', 'worth-watching': '🟡', 'niche': '⚪', 'skip': '🔴' }[app.recommendation] || '⚪';
      const badgeLabel = { 'strong-candidate': 'Strong candidate', 'worth-watching': 'Worth watching', 'niche': 'Niche', 'skip': 'Skip' }[app.recommendation] || app.recommendation;

      lines.push(`## ${badge} ${app.app_name || app.title} — ${app.total_score}/100`);
      lines.push('');
      lines.push(`**URL:** ${app.url || app.app_url}`);
      lines.push(`**Type:** ${app.app_type || 'unknown'} · **Recommendation:** ${badgeLabel}`);
      lines.push('');
      lines.push(app.summary || '');
      lines.push('');
      lines.push('### Scores');
      lines.push('');
      lines.push('| Criterion | Score | Notes |');
      lines.push('|---|---|---|');

      const criteria = [
        ['novelty', 'Novelty'],
        ['system_requirements', 'System requirements'],
        ['current_relevance', 'Current relevance'],
        ['differentiation', 'Differentiation'],
        ['community', 'Community'],
        ['ease_of_use', 'Ease of use'],
        ['ease_of_integration', 'Ease of integration'],
        ['documentation', 'Documentation'],
        ['maturity', 'Maturity'],
        ['performance', 'Performance'],
      ];

      for (const [key, label] of criteria) {
        const s = scores[key];
        if (s) {
          const bar = '█'.repeat(s.score) + '░'.repeat(10 - s.score);
          lines.push(`| ${label} | ${s.score}/10 ${bar} | ${s.justification || ''} |`);
        }
      }

      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  lines.push(`*Generated by [LLM Daily Review](https://github.com/vfalbor/llm-daily-review) · CC BY 4.0*`);

  const markdown = lines.join('\n');
  const reportPath = path.join(REPORTS_DIR, `${date}.md`);
  fs.writeFileSync(reportPath, markdown, 'utf8');

  // Persist to DB
  saveDailyRun(date, {
    found: apps.length + skipped,
    tested: apps.length,
    skipped,
  }, markdown);

  return { markdown, reportPath };
}
